apiVersion: apps/v1
kind: Deployment
metadata: { name: order-service-green }
spec:
  replicas: 0
  selector: { matchLabels: { app: order-service, version: green } }
  template:
    metadata: { labels: { app: order-service, version: green } }
    spec:
      containers:
        - name: order-service
          image: divyanjaliperera/order-service:latest
          ports: [ { containerPort: 8000 } ]
          readinessProbe: { httpGet: { path: /docs, port: 8000 }, initialDelaySeconds: 5, periodSeconds: 5 }
          livenessProbe:  { httpGet: { path: /docs, port: 8000 }, initialDelaySeconds: 10, periodSeconds: 10 }
          resources:
            requests: { cpu: "250m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }
