apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: divyanjaliperera/analytics-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: CLICKHOUSE_HOST
              value: "clickhouse-server"
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_DATABASE
              value: "analytics"
            - name: CLICKHOUSE_USERNAME
              value: "default"
            - name: CLICKHOUSE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

